/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Dashboard2RouteImport } from './routes/dashboard2'
import { Route as MemoryGalleryRouteImport } from './routes/memory-gallery'
import { Route as OwnerDashboardRouteImport } from './routes/owner-dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Dashboard2Route = Dashboard2RouteImport.update({
  id: '/dashboard2',
  path: '/dashboard2',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryGalleryRoute = MemoryGalleryRouteImport.update({
  id: '/memory-gallery',
  path: '/memory-gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerDashboardRoute = OwnerDashboardRouteImport.update({
  id: '/owner-dashboard',
  path: '/owner-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard2': typeof Dashboard2Route
  '/memory-gallery': typeof MemoryGalleryRoute
  '/owner-dashboard': typeof OwnerDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard2': typeof Dashboard2Route
  '/memory-gallery': typeof MemoryGalleryRoute
  '/owner-dashboard': typeof OwnerDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard2': typeof Dashboard2Route
  '/memory-gallery': typeof MemoryGalleryRoute
  '/owner-dashboard': typeof OwnerDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard2' | '/memory-gallery' | '/owner-dashboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard2' | '/memory-gallery' | '/owner-dashboard'
  id: '__root__' | '/' | '/dashboard2' | '/memory-gallery' | '/owner-dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Dashboard2Route: typeof Dashboard2Route
  MemoryGalleryRoute: typeof MemoryGalleryRoute
  OwnerDashboardRoute: typeof OwnerDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard2': {
      id: '/dashboard2'
      path: '/dashboard2'
      fullPath: '/dashboard2'
      preLoaderRoute: typeof Dashboard2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory-gallery': {
      id: '/memory-gallery'
      path: '/memory-gallery'
      fullPath: '/memory-gallery'
      preLoaderRoute: typeof MemoryGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner-dashboard': {
      id: '/owner-dashboard'
      path: '/owner-dashboard'
      fullPath: '/owner-dashboard'
      preLoaderRoute: typeof OwnerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Dashboard2Route: Dashboard2Route,
  MemoryGalleryRoute: MemoryGalleryRoute,
  OwnerDashboardRoute: OwnerDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
